package service;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'next' at '10/4/17 12:23 PM' with Gradle 3.0
 *
 * @author next, @date 10/4/17 12:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
